auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  log_format: json
  log_level: warn

ingester:
  wal:
    enabled: true
    dir: /tmp/loki/wal

storage_config:
  object_prefix: loki/
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache

schema_config:
  configs:
  - from: 2024-01-01
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

compactor:
  working_directory: /tmp/loki/compactor

common:
  storage:
    s3:
      s3forcepathstyle: true
      bucketnames: observability
      endpoint: minio:9000
      access_key_id: ${MINIO_USERNAME}
      secret_access_key: ${MINIO_PASSWORD}
      insecure: true
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
  instance_addr: 127.0.0.1
