server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3200
  log_format: json
  log_level: warn

distributor:
  receivers:
    otlp:
      protocols:
        grpc:

metrics_generator:
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://mimir:9009/api/v1/push
        send_exemplars: true

storage:
  trace:
    backend: s3
    s3:
      bucket: observability
      prefix: tempo
      endpoint: minio:9000
      access_key: ${MINIO_USERNAME}
      secret_key: ${MINIO_PASSWORD}
      insecure: true
    wal:
      path: /tmp/tempo/wal

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]