clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/promtail/positions.yml

scrape_configs:
- job_name: docker
  pipeline_stages:
    - decolorize:
    - docker: {}
  relabel_configs:
    - source_labels: ['__meta_docker_container_id']
      target_label: 'container_id'
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)_.*\.\d+\..*'
      target_label: 'stack'
    - source_labels: ['__meta_docker_container_name']
      regex: '/.*_(.*)\.\d+\..*'
      target_label: 'service_name'
    - source_labels: ['__meta_docker_container_log_stream']
      target_label: 'stream'
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 10s
